const sessionKey = 'pepego_admin_session'; let token = sessionStorage.getItem(sessionKey) || '';
const loginView = document.getElementById('login-view'), dashboardView = document.getElementById('dashboard-view');
const adminActions = document.createElement('div');
adminActions.className = 'admin-actions';
document.getElementById('logout').before(adminActions);
adminActions.append(document.getElementById('logout'));
adminActions.insertAdjacentHTML('afterbegin', '<a class="button-link" href="cotizador.html">Cotizador</a>');
const showMessage = (id, text, success = false) => { const el = document.getElementById(id); el.textContent = text; el.classList.toggle('success', success); };
const money = value => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(value || 0));
async function loadDashboard() { try { const data = await PepeGoApi.dashboard(token); loginView.hidden = true; dashboardView.hidden = false; document.getElementById('dashboard-stats').innerHTML = `<div class="stat"><strong>${data.stats.viajes}</strong><span>Viajes registrados</span></div><div class="stat"><strong>${money(data.stats.cobrado)}</strong><span>Total cobrado</span></div><div class="stat"><strong>${money(data.stats.pendiente)}</strong><span>Saldo por cobrar</span></div>`; document.getElementById('trips-table').innerHTML = data.trips.map(t => `<tr><td>${t.folio}</td><td>${t.nombre}</td><td>${t.destino}</td><td>${t.fechaSalida || '—'}</td><td>${money(t.saldoPendiente)}</td><td><span class="small-status">${t.estatus}</span></td></tr>`).join('') || '<tr><td colspan="6">Aún no hay viajes.</td></tr>'; } catch (_) { sessionStorage.removeItem(sessionKey); token=''; loginView.hidden=false; dashboardView.hidden=true; } }
document.getElementById('login-form').addEventListener('submit', async e => { e.preventDefault(); try { const data = await PepeGoApi.login(document.getElementById('password').value); token = data.token; sessionStorage.setItem(sessionKey, token); await loadDashboard(); } catch(error) { showMessage('login-message', error.message); } });
document.getElementById('trip-form').addEventListener('submit', async e => { e.preventDefault(); const form=e.currentTarget, button=form.querySelector('button'); button.disabled=true; try { await PepeGoApi.saveTrip(Object.fromEntries(new FormData(form)), token); form.reset(); showMessage('trip-message','Viaje guardado correctamente.',true); await loadDashboard(); } catch(error) { showMessage('trip-message',error.message); } finally { button.disabled=false; } });
document.getElementById('payment-form').addEventListener('submit', async e => { e.preventDefault(); const form=e.currentTarget, button=form.querySelector('button'); button.disabled=true; try { await PepeGoApi.registerPayment(Object.fromEntries(new FormData(form)), token); form.reset(); showMessage('payment-message','Pago registrado y saldo actualizado.',true); await loadDashboard(); } catch(error) { showMessage('payment-message',error.message); } finally { button.disabled=false; } });
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem(sessionKey);location.reload()};document.getElementById('refresh').onclick=loadDashboard;if(token) loadDashboard();
